version: '3.7'

services:
  angular:
    build: ./projectCloudAPI
    ports:
      - 8080:80
    restart: unless-stopped
  
  api:
    build: ./RestAPI
    ports:
      - 8081:80
    restart: unless-stopped